apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyztech-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyztech-app
  template:
    metadata:
      labels:
        app: xyztech-app
    spec:
      containers:
      - name: tech-app
        image: nrawal2024/tech_app:v2
        ports:
        - containerPort: 8080
